"""user_id and room_id is nulable false

Revision ID: 30df388e1397
Revises: 2dab0ccdb4dc
Create Date: 2023-08-16 19:22:18.974225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30df388e1397'
down_revision = '2dab0ccdb4dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
