"""fix total cost, cost

Revision ID: 8f217ee4c55b
Revises: 7d3b9049147b
Create Date: 2023-07-30 13:28:38.997334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f217ee4c55b'
down_revision = '7d3b9049147b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
