services:
  server:
    container_name: nginx
    image: nginx:1.25
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:14.7
    container_name: postgres
    ports: 
      - 6543:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  redis:
    image: redis:7
    container_name: redis

  backend:
    container_name: backend
    build: .
    depends_on:
      - db
      - redis
      - server
    command: ["sh", "bash/backend.sh"]

  celery:
    container_name: celery
    depends_on:
      - backend
      - redis
      - server
    build: .
    command: ["sh", "bash/celery.sh"]
